### ISSUE TITLE
How to pass a file to convert json2csv

### ISSUE THREAD

**Issue by GaganMeesala** [netbe/Babelish#102]
Conversion of json file to csv.

Tried
babelish json2csv  1.json
babelish json2csv  "1.json"

**Comment by netbe** [comment]
Hi,

sorry for the late replied, have you tried:
```
babelish json2csv --filename=1.json
```

The best is to use a configuration, the rest of documentation can be found here : 
https://github.com/netbe/Babelish/wiki/How-to-Use

**Comment by GaganMeesala** [comment]
Tried, still not working:

Error:

ERROR: "babelish json2csv" was called with arguments ["--filename=~/Desktop/1.json"]
Usage: "babelish json2csv"
