### ISSUE TITLE
csv2android: default values folder

### ISSUE THREAD

**Issue by BlackHornet** [netbe/Babelish#105]
I think it would be good, if you can configure babelish with a "default language" so the language code is not added to the folders name. Like a fallback language, if everything other fails.

for example:
```
langs:                               # Languages to convert. i.e. English:en
  English: "en"
  French: "fr"
default_lang: English      # new option
```

Current created folders by babelish:
```
values-en
values-fr
```

Expected folders to be created:
```
values
values-fr
```

Kind regards

**Comment by netbe** [comment]
@BlackHornet well the default_lang option already exist. I have no opinion on this change as I don't use it for android.

Here's the code to change https://github.com/netbe/Babelish/blob/master/lib/babelish/csv2android.rb#L12-L17

Feel free to do a PR including tests :)

**Comment by scinfu** [comment]
@netbe this problem persists, has it been solved?
