### ISSUE TITLE
convert json to csv

### ISSUE THREAD

**Issue by GaganMeesala** [netbe/Babelish#106]
babelish json2csv --filename=~/Desktop/1.json

Tried, still not working:

Error:

ERROR: "babelish json2csv" was called with arguments ["--filename=~/Desktop/1.json"]
Usage: "babelish json2csv"

**Comment by netbe** [comment]
So, I had a closer look, and add some documentation over here:

https://github.com/netbe/Babelish/wiki/Examples

In the process, I found one issue which is fixed in this new release:

https://github.com/netbe/Babelish/releases/tag/0.5.4

Let me know if that works for you.
