### ISSUE TITLE
Problem converting csv to xml (android)

### ISSUE THREAD

**Issue by gsantoscarrot** [netbe/Babelish#112]
Traceback (most recent call last):
14: from C:/Ruby25-x64/bin/babelish:23:in <main>' 13: from C:/Ruby25-x64/bin/babelish:23:in load'
12: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/babelish-0.5.4/bin/babelish:6:in <top (required)>' 11: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in start'
10: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in dispatch' 9: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in invoke_command'
8: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in run' 7: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/babelish-0.5.4/lib/babelish/commandline.rb:38:in block (2 levels) in class:Commandline'
6: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/babelish-0.5.4/lib/babelish/commandline.rb:150:in csv2base' 5: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/babelish-0.5.4/lib/babelish/commandline.rb:150:in each_with_index'
4: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/babelish-0.5.4/lib/babelish/commandline.rb:150:in each' 3: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/babelish-0.5.4/lib/babelish/commandline.rb:157:in block in csv2base'
2: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/babelish-0.5.4/lib/babelish/commandline.rb:157:in new' 1: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/babelish-0.5.4/lib/babelish/csv2android.rb:6:in initialize'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/babelish-0.5.4/lib/babelish/csv2base.rb:26:in `initialize': wrong value of filename: nil (ArgumentError)

I have ruby 2.5.5p157 (2019-03-15 revision 67260) [x64-mingw32]

**Comment by netbe** [comment]
Hi @gsantoscarrot, can you post the command you are using and csv file?

**Comment by gsantoscarrot** [comment]
![Screenshot (68)](https://user-images.githubusercontent.com/48450753/56736926-5fd27100-6737-11e9-82ec-64f640f3feaf.png)

**Comment by gsantoscarrot** [comment]
This file I got from your github Babelish-master\test\data\test_data_with_comments.csv
and the command is: babelish csv2android

**Comment by netbe** [comment]
Ok I see, well csv2android requires 2 arguments, here it needs the filename to read from  and the languages to use:

```
 babelish csv2android --filename=test_data_multiple_langs.csv --langs English:en,German:de, French:fr,Spanish:es
```
 
See the documentation here https://github.com/netbe/Babelish/wiki/How-to-Use

**Comment by gsantoscarrot** [comment]
with this file **test_data_multiple_langs.csv** your command **babelish csv2android --filename=test_data_multiple_langs.csv --langs English:en,German:de, French:fr,Spanish:es** worked, but I tried the same with this file **test_data_with_comments.csv** and not works, what I need to change?

**Comment by netbe** [comment]
you need to specify filename and the languages contained in your csv that you want to extract to. In my example the csv contain a header with the languages listed like Englishm German etc and then en, de are used to create the output files

**Comment by gsantoscarrot** [comment]
**In my case, if I remove Comments worked**
**Original file**
variables,English,German,French,Spanish,**_Comments_**GREETINGS,Hello,Hallo,Salut,Buenos dias,**_this is a greeting string_**ANOTHER_STRING,testEN,,,,**_this is another example_**

**file without comments**
variables,English,German,French,SpanishGREETINGS,Hello,Hallo,Salut,Buenos diasANOTHER_STRING,testEN,,,,

**used commands all worked**
babelish csv2android --filename=test_data_with_comments.csv --langs English:en,German:de,French:fr,Spanish:es
babelish csv2android --filename=test_data_with_comments.csv --langs English:en,German:de,French:fr
babelish csv2android --filename=test_data_with_comments.csv --langs English:en,German:de
babelish csv2android --filename=test_data_with_comments.csv --langs English:en

**Comment by jschisler** [comment]
You'll need to specify the column that has the comments in it, which I have specified in the config file

**Comment by netbe** [comment]
@gsantoscarrot as @jschisler said, you have to specify the comments column number with `-C 5` or `--comments-column=5` in your example.

see `babelish help csv2strings` for more info
