### ISSUE TITLE
How to use `output_basenames`?

### ISSUE THREAD

**Issue by daniavram** [netbe/Babelish#113]
Hi. Is there any way you could update the Wiki with a guide on how to use `output_basenames` specifically? I have a Google Sheet, provided three `output_basenames` in the config file but only the first one is taken into account. Should there be a column in the Google Sheet which tells babelish which row to export to which output file? I am exporting for iOS, by the way.

**Comment by netbe** [comment]
Hi @daniavram, 
the option `output_basenames` is used only if you have multiple sheets in your google spreadsheet.
So given you have in your doc two sheets named and the option `output_basenames` is provided:
```
output_basenames: 
  - Localizable
  - info
```
The first sheet will produce files en.lproj/Localizable.strings, de.lproj/Localizable.strings ... for example
The second sheet will produce files en.lproj/info.strings, de.lproj/info.strings  
(given that the two sheets contain English and German columns)


Hope that helps ;)

**Comment by daniavram** [comment]
Hi, @netbe,

It does help, indeed. Thank you 🙂 
Thing is that i **did** have multiple sheets in my Google Doc, but I also had the `sheet: 0` option in the config file. I removed that and after that `output_basenames` worked as intended

Merci and kudos for this cool tool 😉
