### ISSUE TITLE
Update google_drive dependency

### ISSUE THREAD

**Issue by borut-t** [netbe/Babelish#114]
Hi @netbe. Could you update `google_drive` dependency version to at least version `2.1.12`.
The reason is that you use `google_drive` version `2.1.7` which internally uses `google-api-client` version `['>= 0.11.0', '< 0.14.0']`. And that is in conflict with [Fastlane](https://github.com/fastlane/fastlane/blob/master/fastlane.gemspec) library which requires version `['>= 0.21.2', '< 0.24.0']`.

**Comment by borut-t** [comment]
@netbe is there an ETA on when 0.6.0 is released?

**Comment by netbe** [comment]
Sorry for the delay @borut-t, releasing 0.5.5 to fix the issue

**Comment by borut-t** [comment]
Thank you 🙌

**Comment by borut-t** [comment]
@netbe trying to make this work, but I'm still facing an issue:
```
Bundler could not find compatible versions for gem "google-api-client":
  In snapshot (Gemfile.lock):
    google-api-client (= 0.23.9)

  In Gemfile:
    fastlane (= 2.126.0) was resolved to 2.126.0, which depends on
      google-api-client (< 0.24.0, >= 0.21.2)

    fastlane (= 2.126.0) was resolved to 2.126.0, which depends on
      google-cloud-storage (< 2.0.0, >= 1.15.0) was resolved to 1.16.0, which depends on
        google-api-client (~> 0.23)

    babelish (= 0.5.5) was resolved to 0.5.5, which depends on
      google_drive (~> 2.1.12) was resolved to 2.1.12, which depends on
        google-api-client (< 0.22.0, >= 0.11.0)
```

I could try downgrading fastlane but I'm not sure if I want to do that 🤔 
Do you have any idea?

**Comment by netbe** [comment]
@borut-t Could you post your gemfile ? I just tryed a simple one and it worked:
```
› more Gemfile                                                                                                                                                                        
# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "fastlane"
gem "babelish"
```

**Comment by netbe** [comment]
oh ok it resolverd to a previous version:
```
    babelish (0.5.2)
      google_drive (~> 1.0.1)
   fastlane (2.128.1)
```
I guess I have to increase the version of google_drive to have google-api-client at (~> 0.23)

**Comment by borut-t** [comment]
@netbe here is my Gemfile:
```
gem 'fastlane', '2.126.0'
gem 'cocoapods', '1.7.5'
gem 'babelish', '0.5.5'
gem 'xcov', '1.5.0'
```

**Comment by borut-t** [comment]
@netbe yeah, can we do that?

**Comment by netbe** [comment]
@borut-t yes I was writing a test to make sure compatibility with fastlane was ensure. I'll ping you as soon as I am done.

**Comment by borut-t** [comment]
Thank you!

**Comment by borut-t** [comment]
Fyi, gems can be installed without an error if I omit the version of the `babelish` gem. It installs 0.5.2. But when I run the script I get the following error:
```
bundler: failed to load command: Babelish (/usr/local/bin/Babelish)
LoadError: cannot load such file -- google/api_client
  /Library/Ruby/Gems/2.3.0/gems/google_drive-1.0.1/lib/google_drive.rb:5:in `require'
  /Library/Ruby/Gems/2.3.0/gems/google_drive-1.0.1/lib/google_drive.rb:5:in `<top (required)>'
  /Library/Ruby/Gems/2.3.0/gems/babelish-0.5.2/lib/babelish/google_doc.rb:7:in `require'
  /Library/Ruby/Gems/2.3.0/gems/babelish-0.5.2/lib/babelish/google_doc.rb:7:in `<module:Babelish>'
  /Library/Ruby/Gems/2.3.0/gems/babelish-0.5.2/lib/babelish/google_doc.rb:1:in `<top (required)>'
  /Library/Ruby/Gems/2.3.0/gems/babelish-0.5.2/lib/babelish.rb:27:in `require'
  /Library/Ruby/Gems/2.3.0/gems/babelish-0.5.2/lib/babelish.rb:27:in `<top (required)>'
  /Library/Ruby/Gems/2.3.0/gems/babelish-0.5.2/bin/babelish:3:in `require'
  /Library/Ruby/Gems/2.3.0/gems/babelish-0.5.2/bin/babelish:3:in `<top (required)>'
  /usr/local/bin/Babelish:22:in `load'
  /usr/local/bin/Babelish:22:in `<top (required)>'
```

So I would say that it wants to load api_client lib but it's too old 🤷‍♂

**Comment by borut-t** [comment]
I was also able to make it work if I didn't specify a version for `fastlane`. But yet again I don't want to downgrade `fastlane` just to make this work.

Long story short, we need to update dependency version for `babelish` to comply with `fastlane`.

**Comment by netbe** [comment]
Hi @borut-t, could you try :
```
gem "babelish", :git => "https://github.com/netbe/Babelish", :branch => "master"
```
before I release the 0.5.6 ?

**Comment by borut-t** [comment]
@netbe I can confirm that the following setup works:
```
gem 'fastlane', '2.128.1'
gem 'cocoapods', '1.7.5'
gem 'xcov', '1.5.0'
#gem 'babelish', '0.5.5'
gem 'babelish', :git => "https://github.com/netbe/Babelish", :branch => "master"
```

If you can prepare a new release that would awesome.

**Comment by borut-t** [comment]
@netbe just tested the 0.5.6 version and it works great with the latest fastlane. Thanks 🙌
