### ISSUE TITLE
How to use csv_download

### ISSUE THREAD

**Issue by bernikovich** [netbe/Babelish#117]
Hi guys.

I'm trying to use `csv_download` function, but there is no documentation about it. I tried multiple formats of setting filename with no luck. Please, help. :)
`babelish csv_download --gd-filename=d/1tD6oG0f_fnVv4ttp17nt1U3xOQ3_v-xxXxXxxxX`

**Comment by netbe** [comment]
Hi @bernikovich ,

You got the correct syntax, but the filename value is really name of the file in google spreadsheets as it is written, not the shared link

ie: for the file: ios_greenstr_strings
```
babelish csv_download --gd-filename=ios_greenstr_strings
```

Hope that helps :)

**Comment by bernikovich** [comment]
Wow, now I dunno how this works. :)
