### ISSUE TITLE
Sign in with Google temporarily disabled for this app

### ISSUE THREAD

**Issue by borut-t** [netbe/Babelish#121]
Trying to authenticate with google to get the token for the first time, it throws an error

<img width="613" alt="Screenshot 2019-11-24 at 20 48 47" src="https://user-images.githubusercontent.com/677166/69500502-05cba100-0efc-11ea-9989-b639d4c9c19c.png">

@netbe can you take a look if your app need some agreement update or smth else in order this to work again?

**Comment by netbe** [comment]
Hi @borut-t, yes I got it too, I am upgrading the gem, and will publish a new version very soon

**Comment by mihbt** [comment]
Hi @netbe! Do you have an estimative date when the update will be rolled out? Any info is much appreciated.

**Comment by netbe** [comment]
@mihbt Worst case before christmas, best case next week, sorry guys I am lacking time to finish this :(

**Comment by pagind92** [comment]
I updated babelish gem to 0.6.1 version, but it seems there is still the authentication error.

This is the error printed in the terminal

babelish-0.6.1/lib/babelish/google_doc.rb:48:in `authenticate': uninitialized constant Babelish::Keys (NameError)

I try to execute babelish with the token previously generated and also removing it to generate a new one, but no success.

**Comment by netbe** [comment]
@pagind92 yes I need to remove 0.6.1, a file is missing from the release, I'll ping you as soon as it's done (probably next week)

**Comment by netbe** [comment]
@pagind92, @borut-t 0.6.2 is out and should be good to go now.

You might see the following screen when requesting a new token, go through it with the link `Go to babelish (unsafe)` 

<img width="981" alt="Screenshot 2019-12-30 16 25 34" src="https://user-images.githubusercontent.com/254198/71589513-6bc3cd80-2b25-11ea-9e77-9dc49f77fd86.png">

**Comment by borut-t** [comment]
Hey @netbe. I've just updated to version 0.6.2 and I get this error:
```
bundler: failed to load command: babelish (/usr/local/bin/babelish)
LoadError: cannot load such file -- babelish/keys
  /Library/Ruby/Gems/2.6.0/gems/babelish-0.6.2/lib/babelish.rb:27:in `require'
  /Library/Ruby/Gems/2.6.0/gems/babelish-0.6.2/lib/babelish.rb:27:in `<top (required)>'
  /Library/Ruby/Gems/2.6.0/gems/babelish-0.6.2/bin/babelish:3:in `require'
  /Library/Ruby/Gems/2.6.0/gems/babelish-0.6.2/bin/babelish:3:in `<top (required)>'
  /usr/local/bin/babelish:23:in `load'
  /usr/local/bin/babelish:23:in `<top (required)>'
```

This is the command: `bundle ex babelish csv2strings`

Do you have any idea what's happening?

**Comment by netbe** [comment]
@borut-t let me check it yeah I thought I fix the travis job to contain the keys.rb file

**Comment by netbe** [comment]
Hi @borut-t, hopefully 0.6.3 is the one !

**Comment by borut-t** [comment]
Version `0.6.3` works now. Thanks, @netbe.

Although I'm not sure why drive API asks us for full access to all files in the drive? Should it only access Spreadsheets?

**Comment by borut-t** [comment]
Hi @netbe. Some developers are again getting a "temporarily disabled" message without a button to continue. I've tried the same on my end today and I was able to get through. Maybe Google randomly forces users into that state.

Can you take a look and see if some google dependency needs to be updated in order to get rid of that message? As I said, some of our developers are unable to get through this message, therefore cannot generate localizations.

Thanks 🙌

**Comment by netbe** [comment]
Hi @borut-t,

I've requested a review from Google to verify the app a while ago so the limit of `user cap (100/100)` could be lifted, and reached out again today, hopefully this will get resolved soon.

```
Your user cap
The user cap limits the number of users that can grant permission to your app when requesting unapproved sensitive or restricted scopes. The user cap applies over the entire lifetime of the project, and it cannot be reset or changed. Verified apps will still display the user cap on this page, but the user cap does not apply if you are requesting only approved sensitive or restricted scopes. If your users are seeing the "unverified app" screen , it is because your OAuth request includes additional scopes that haven't been approved.
```

Sorry for the inconvenience

**Comment by borut-t** [comment]
@netbe any news on that?

**Comment by netbe** [comment]
Hi @borut-t,

Sorry I had no time to work on it. Google asked me a bunch of information including a video showing the app in action which I just made. I hope this is the last requirement to lift the limit and solve this issue.

**Comment by borut-t** [comment]
Thanks, @netbe. I completely understand your situation. Keeping fingers crossed it will go through this time 🤞 
Lmk when you resolve this issue.

**Comment by netbe** [comment]
Hi @borut-t, I finally got it to work, you'll find a new release 0.6.5

**Comment by borut-t** [comment]
Thanks @netbe 🎉
