### ISSUE TITLE
Google disabled this app

### ISSUE THREAD

**Issue by dbeleza** [netbe/Babelish#127]
Hi.
Today I noticed an issue related with Babelish.
After I run `babelish csv2android` and open the generated link, google is presenting this warning:
![image](https://user-images.githubusercontent.com/4144018/78694321-65977700-78f4-11ea-8277-c641270302c3.png)

Do you know how to fix this?

Thanks in advance

**Comment by netbe** [comment]
@dbeleza can you specifythe version of babelish you're using ? 
```
babelish version
```

0.6.3 normally fixed this issue

**Comment by AgapovOne** [comment]
After passing this alert from google I do get an auth code, but the script doesn't accept it.

Here is what I get. Everything worked before that.
```bash
gnet::AuthorizationError: Authorization failed.  Server message:
{
  "error": "invalid_grant",
  "error_description": "Bad Request"
}
  /usr/local/lib/ruby/gems/2.6.0/gems/signet-0.14.0/lib/signet/oauth_2/client.rb:1039:in `fetch_access_token'
  /usr/local/lib/ruby/gems/2.6.0/gems/signet-0.14.0/lib/signet/oauth_2/client.rb:1054:in `fetch_access_token!'
  /usr/local/lib/ruby/gems/2.6.0/gems/googleauth-0.11.0/lib/googleauth/signet.rb:80:in `block in fetch_access_token!'
  /usr/local/lib/ruby/gems/2.6.0/gems/googleauth-0.11.0/lib/googleauth/signet.rb:107:in `retry_with_error'
  /usr/local/lib/ruby/gems/2.6.0/gems/googleauth-0.11.0/lib/googleauth/signet.rb:79:in `fetch_access_token!'
  /usr/local/lib/ruby/gems/2.6.0/gems/google_drive-3.0.4/lib/google_drive/session.rb:170:in `from_config'
  /usr/local/lib/ruby/gems/2.6.0/gems/google_drive-3.0.4/lib/google_drive.rb:31:in `saved_session'
  /usr/local/lib/ruby/gems/2.6.0/gems/babelish-0.6.3/lib/babelish/google_doc.rb:46:in `authenticate'
  /usr/local/lib/ruby/gems/2.6.0/gems/babelish-0.6.3/lib/babelish/google_doc.rb:54:in `file_with_name'
  /usr/local/lib/ruby/gems/2.6.0/gems/babelish-0.6.3/lib/babelish/google_doc.rb:28:in `download_spreadsheet'
  /usr/local/lib/ruby/gems/2.6.0/gems/babelish-0.6.3/lib/babelish/commandline.rb:121:in `download'
  /usr/local/lib/ruby/gems/2.6.0/gems/babelish-0.6.3/lib/babelish/commandline.rb:140:in `csv2base'
  /usr/local/lib/ruby/gems/2.6.0/gems/babelish-0.6.3/lib/babelish/commandline.rb:38:in `block (2 levels) in <class:Commandline>'
  /usr/local/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
  /usr/local/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
  /usr/local/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
  /usr/local/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
  /usr/local/lib/ruby/gems/2.6.0/gems/babelish-0.6.3/bin/babelish:6:in `<top (required)>'
  /usr/local/lib/ruby/gems/2.6.0/bin/babelish:23:in `load'
  /usr/local/lib/ruby/gems/2.6.0/bin/babelish:23:in `<top (required)>'
```

**Comment by dbeleza** [comment]
Hi @netbe,
Sorry for just answering to you now.
I'm using version 0.6.3. And I'm still getting this error from google when I open the generated link.
Thanks for helping me

**Comment by netbe** [comment]
Hi @dbeleza ,

The app is not verified by Google but it should not stop you to use it normally there is a link to to use anyway in the bottom, see:

![Screenshot 2020-04-16 at 15 43 27](https://user-images.githubusercontent.com/254198/79463477-315d3e00-7ff9-11ea-9fad-735dcdf9b033.png)

![Screenshot 2020-04-16 at 15 43 32](https://user-images.githubusercontent.com/254198/79463536-44700e00-7ff9-11ea-84c3-877908e564b3.png)

![Screenshot 2020-04-16 at 15 43 41](https://user-images.githubusercontent.com/254198/79463585-4e920c80-7ff9-11ea-9735-e026ea25b4b0.png)

PS: if the app is not showing the auth link, remove the `.babelish.token` file in your folder.

I've just requested verification to avoid this issue, i'll post here when it's approved.

**Comment by dbeleza** [comment]
You're right! Thanks a lot once again! 🙇‍♂️
