### ISSUE TITLE
Cannot found client_secret for Android Application when creating OAuth Client Id.

### ISSUE THREAD

**Issue by RyanNguyen92** [netbe/Babelish#139]
Hi,

I would like to use this library, I just got the issue as bellow, please help to take a look:

- I created web application Client Id from https://console.developers.google.com/apis/credentials and receive the client id and secret key.

But when tries to run 'localize' script via terminal and open the link in browser, then the issue appeared like the image.

I know that we need to create Client Id for native application.

But when I creates client id for Android/iOS , then I cannot found any secret key to use.

Anyone resolve this?

Thanks.
![Screen Shot 2020-07-14 at 11 36 57](https://user-images.githubusercontent.com/58189811/87384695-96a7d780-c5c6-11ea-8952-5756a62ff11d.png)

**Comment by netbe** [comment]
Hi @RyanNguyen92,

Normally you don't have to create a web app client, Babelish has one already, the issue might be related to #121.
