### ISSUE TITLE
Omit Empty translations CSV2Any

### ISSUE THREAD

**Issue by GrzesiekZbozien** [netbe/Babelish#140]
Hi is there any way to omit empty translations during import?

Example:

`labels.example,Example in Default lang, Other Lang,,,,,,,,,,,`
And to prevent for non translated languages yet:
in iOS:
`"labels.example" = "";`
and Android:
`<string name="labels.example"></string>`

**Comment by netbe** [comment]
Hi, 

You cannot omit, but you can replace empty values by a translated languages value, see option: `default_lang`

https://github.com/netbe/Babelish/blob/137a0f9886d994ce2578a2c7d7c243b609b3f0b4/.babelish.sample#L26

**Comment by GrzesiekZbozien** [comment]
Thanks for response, I'll check it. Seems like good enough for me.
