### ISSUE TITLE
Custom CSV2STRINGS -> cannot load such file -- babelish/keys

### ISSUE THREAD

**Issue by Saulenco** [netbe/Babelish#143]
Hi, i'm trying to change the csv2strings file because we use same csv on android and ios .

i have updated the `get_row_format` like so: 
```
 def get_row_format(row_key, row_value, comment = nil, indentation = 0)
      if row_value.empty?
        ""
      else
        entry = comment.to_s.empty? ? "" : "\n/* #{comment} */\n"
        curr_value = row_value.gsub('%s', '%@').gsub('$s', '$@')
        curr_value = curr_value.gsub('&amp;', '&').gsub('&#8230;', '...')
        entry + "\"#{row_key}\"" + " " * indentation + " = \"#{curr_value}\";\n"
      end
    end
```

and it worked fine till some days back. 

what i'm doing wrong ?

1. uninstall previouns babelish `sudo gem uninstall babelish`
2. download new code
3. update the `csv2strings.rb` file
4. build new gem `sudo gem build babelish.gemspec `
5. install new gem that was built `sudo gem install babelish-0.6.6.gem `
6. call csv2strings `babelish csv2strings` and receive an error

```
	7: from /usr/local/bin/babelish:23:in `<main>'
	6: from /usr/local/bin/babelish:23:in `load'
	5: from /Library/Ruby/Gems/2.6.0/gems/babelish-0.6.6/bin/babelish:3:in `<top (required)>'
	4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	2: from /Library/Ruby/Gems/2.6.0/gems/babelish-0.6.6/lib/babelish.rb:27:in `<top (required)>'
	1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- babelish/keys (LoadError)
```

event if i call `babelish -v` i receive the same error

**Comment by netbe** [comment]
Hello, the token to access google apis is built on CI and is not available that's why you can't build the gem yourself
If you want to continue you will have to create yourself the keys file including a different google_apis access_token.
