### ISSUE TITLE
can't read text when convert japanese

### ISSUE THREAD

**Issue by TienDungDoan** [netbe/Babelish#144]
I tried to convert file Localized.strings(japanese) to csv using command "strings2csv". It's work but I cant read text in csv. Output is below:
aaa	‰ΩøÁî®Ë®±Ë´æ„Å∏ÂêåÊÑè„ÅÆ„ÅîÁ¢∫Ë™ç
bbb	ÂêåÊÑè„Åó„Å¶ÁôªÈå≤ÁîªÈù¢„Å∏ÈÄ≤„ÇÄ

Because key is english so its ok but value is error. Anybody can tell me what im wrong ???

**Comment by netbe** [comment]
Hi, can you post your .strings files and config?

**Comment by TienDungDoan** [comment]
Hi, I sent my content in .strings file below and I don't use config file, I just run terminal command "babelish strings2csv --filenames= Localizable.strings"
"aaa" = "戻る";
"bbb" = "作成";
And there is result in .csv file:
<img width="197" alt="Screen Shot 2021-12-08 at 14 52 47" src="https://user-images.githubusercontent.com/13981868/145169782-02f959ec-9776-44f0-9274-c203c4e18fa7.png">

**Comment by netbe** [comment]
Works fine to me, see console steps below:
![Screenshot 2021-12-09 at 16 38 42](https://user-images.githubusercontent.com/254198/145427193-be0fb79a-5491-4355-b8ba-4c1db6b5a608.png)

**Comment by netbe** [comment]
What's your operating system? version?

**Comment by TienDungDoan** [comment]
I'm using Macos Catalina 10.15.4 and babelish version is 0.6.6 .
 And I try to use another computer run Macos BigSur 11.5.2 then I see same error.

**Comment by netbe** [comment]
can you please attach the file you're using?
