### ISSUE TITLE
Look at .stringsdict support

### ISSUE THREAD

**Issue by netbe** [netbe/Babelish#40]
see article http://www.objc.io/issue-9/working-with-strings.html

**Comment by Fl0p** [comment]
👍 
Vote-Up for this reopen.

**Comment by netbe** [comment]
@Fl0p I would need some help to support it, I don't see how the csv structure would be suitable to have the `.stringsdict`, do you have something to start with?

**Comment by Fl0p** [comment]
@netbe i suppose it is possible to create some kind on naming convention for CVS files.
So that every plural form (zero, one, two, few, many, and other) will be a separated string in csv.

```
keys, en, ru;
BabelishPluralDefault $d sec(s) remaining, $d second(s) remaining, $d секунд осталось;
BabelishPluralZero $d sec(s) remaining, time is up, время вышло;
BabelishPluralOne $d sec(s) remaining, $d second remaining, $d секунда осталось;
BabelishPluralTwo $d sec(s) remaining, $d seconds remaining, $d секунды осталось;
BabelishPluralMany $d sec(s) remaining, $d seconds remaining, $d секунд осталось;
BabelishPluralOther $d sec(s) remaining, $d seconds remaining, $d секунд осталось;
```

So it will fine for converting in ```.stringsdict``` for iOS as well as ```.xml``` for Adnoid

**Comment by netbe** [comment]
@Fl0p I don't have any time now to work on that, and would need to look again to .stringsdict structure. 

But if you feel like contributing I can support with the code base.
