### ISSUE TITLE
CSV column separator style

### ISSUE THREAD

**Issue by borut-t** [netbe/Babelish#55]
For some reason Pages and Word exports to CSV with semicolon ";" column separator. On the other hand Google Docs exports with comma "," column separator.

Is it possible to define custom column separator?

**Comment by netbe** [comment]
Right now it is not possible, but adding an option for separator could be done.

See https://github.com/netbe/Babelish/blob/master/lib/babelish/csv2base.rb#L92

I do not plan to do it soon, but feel free to do a pull request for it :)

**Comment by borut-t** [comment]
That would be really great. I have a csv file that already contains comma characters in translation strings. When I replace ";" with "," your tool breaks becase there are to many columns in csv (obviously).

How can I do it myself so I can use it in project today? Is it possible to update gem today? Can I help?

**Comment by netbe** [comment]
Fork the project and create a pull request. 
- pass an option here like `separator` https://github.com/netbe/Babelish/blob/master/lib/babelish/commandline.rb#L23 default would be ,
- and in here  https://github.com/netbe/Babelish/blob/master/lib/babelish/csv2base.rb#L92 replace , by ;
- write a test case to make sure you didn't break anything and it is working

**Comment by borut-t** [comment]
Ok, I've made some changes and requested pull request: https://github.com/netbe/Babelish/pull/56

Could you check it out?

**Comment by borut-t** [comment]
Just checking... Could you review and merge pull request so I can use it in my development team?

**Comment by netbe** [comment]
Included in 0.3.4

**Comment by netbe** [comment]
@borut-t please use 0.3.4

**Comment by borut-t** [comment]
Nice, thank you!
