### ISSUE TITLE
As a suggestion: .csv or Google Docs example

### ISSUE THREAD

**Issue by fabioknoedt** [netbe/Babelish#58]
Hi @netbe,

Thanks for the nice library!
As a suggestion, could you add a .csv file and/or Google Docs file as example?
It would be nice to have a .csv file as example and how to call it to generate .strings files, for example.

I was wondering how to escape some rows and I couldn't find a way.

Cheers!

**Comment by netbe** [comment]
Hi,

I am not sure if this helps but on the test data folder there are some examples like: https://github.com/netbe/Babelish/blob/master/test/data/test_data_multiple_langs.csv
And to generate a .strings file, the command would be:
```
babelish csv2strings --filename test_data_multiple_langs.csv --langs English:en,German:de, French:fr,Spanish:es
```

The command should tell you what arguments are required.

Hope that helps!

**Comment by fabioknoedt** [comment]
It indeed helps! I would provide a more complex one, but this helps already.
It would be super if you write about this example in the README :) for other people.
Let me know if you don't have time and I can also do it and create a pull request.

Btw, for someone that lands here:
I could escape rows using the configuration:
1. In the row I want to escape I write **ESCAPE** (for example) in the column **0**
2. In your .babelish file I added: *state_column: 0*
3. In your .babelish file I added: *excluded_states: ["ESCAPE"]*

Then, when you run:
`babelish csv2strings --filename test_data_multiple_langs.csv --langs English:en,German:de, French:fr,Spanish:es`

The parser ignores every line that has **ESCAPE** in the first column (column=0).

**Comment by netbe** [comment]
@fabioknoedt pull requests are, indeed, very welcome :) 

FYI I usually don't use the command arguments but use a config file on project, I don't know if you have seen this section (example file: https://github.com/netbe/Babelish/blob/master/.babelish.sample )

**Comment by fabioknoedt** [comment]
Done. I hope it's alright for you. If not, change anything you would like to.
Thanks man!
