### ISSUE TITLE
Better file not exists error handling

### ISSUE THREAD

**Issue by Neoklosch** [netbe/Babelish#75]
Similar to the xml error problem I got an error if the file I want to convert doesn't exist.
I got the following error:

	$ babelish android2csv --filenames=/tmp/android.xml --csv-filename=/tmp/android_run2.csv --headers=Vars German
	
	/home/neoklosch/ruby-projects/Babelish/lib/babelish/android2csv.rb:11:in `load_strings': No such file or directory (Errno::ENOENT)
	from /home/neoklosch/ruby-projects/Babelish/lib/babelish/base2csv.rb:31:in `block in convert'
	from /home/neoklosch/ruby-projects/Babelish/lib/babelish/base2csv.rb:29:in `each'
	from /home/neoklosch/ruby-projects/Babelish/lib/babelish/base2csv.rb:29:in `convert'
	from /home/neoklosch/ruby-projects/Babelish/lib/babelish/commandline.rb:165:in `base2csv'
	from /home/neoklosch/ruby-projects/Babelish/lib/babelish/commandline.rb:56:in `block (2 levels) in <class:Commandline>'
	from /home/neoklosch/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /home/neoklosch/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/neoklosch/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /home/neoklosch/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/neoklosch/ruby-projects/Babelish/bin/babelish:6:in `<top (required)>'
	from /home/neoklosch/.rvm/gems/ruby-2.1.5/bin/babelish:23:in `load'
	from /home/neoklosch/.rvm/gems/ruby-2.1.5/bin/babelish:23:in `<main>'
	from /home/neoklosch/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
	from /home/neoklosch/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'

A propper error handling would be helpful.

**Comment by tkbky** [comment]
@netbe I can help out on this. I'm thinking of rescuing `Errno::ENOENT` and output the error message to `STDERR`, WDTY?

**Comment by netbe** [comment]
Yep that would be great, ideally the messages output should be done in the `commandline` file I think
