### ISSUE TITLE
Comments support on android

### ISSUE THREAD

**Issue by borut-t** [netbe/Babelish#83]
Is there a way to integrate comments into generated files on android like it already works on iOS ?

Thanks!

**Comment by netbe** [comment]
Support for Android could be added, I don't know how comments are formatted in Android xml files, but if you know it, one starting point to implement it (CSV to android) would be `get_row_format` https://github.com/netbe/Babelish/blob/master/lib/babelish/csv2android.rb#L27-L29

For the other way around, it would be to modify https://github.com/netbe/Babelish/blob/master/lib/babelish/android2csv.rb the same way https://github.com/netbe/Babelish/blob/master/lib/babelish/strings2csv.rb does it.

**Comment by borut-t** [comment]
I've just made a pull request #84.
