### ISSUE TITLE
Dockerise usage

### ISSUE THREAD

**Issue by netbe** [netbe/Babelish#92]

**Comment by andela-ooranagwa** [comment]
Could you provide some more information for this issue. I would want to work on it.

**Comment by netbe** [comment]
Basically it would be to wrap babelish to a docker container, so people can use it via docker without having ruby installed on their machine.

So needs to be done:

- create dockerfile
- documentation how to run it: i.e. `docker run netbe/babelish csv2strings...` or something like that
