### ISSUE TITLE
config file keys_column

### ISSUE THREAD

**Issue by Saulenco** [netbe/Babelish#95]
I added the .babelish.config file and the keys_column:2 because the keys in my google drive file starts from 2nd row.

this is my sructure:
`Category | Key | English | Notes`

Run `babelish csv2strings -i "Project Language" -L  English:en  --fetch `

the .string file looks like this
"category1" = "";
"category2" = "";
....

Did i miss something ?

**Comment by netbe** [comment]
Hi,

if you're using the config file you don't need to pass arguments via command line.
Your config file could look like this:

```
filename:  "Project Language"    
langs:                               
  English: "en"

## optional
fetch: true                        # set to true to get file(filename) from google drive
comments_column: 3                 # Position of column for comments if any
keys_column: 1                     # Position of column for keys
```

By the way is `Project Language` the filename (path) to your csv file?

**Comment by Saulenco** [comment]
"Project Language" is the file name on Google Drive. 

 after adding the configs as you show and run `babelish csv2strings` i get an error  `in `initialize': wrong value of filename: nil` also tried 
```
 filename: "translations_Sheet1.csv"
# fetch: true 
```
but i get the same error

**Comment by Saulenco** [comment]
Got it the main problem was that my babelish config file was named `.babelish.config` rename it to `.babelish` run `babelish csv2strings` and problem solved.

Thanks again François
